image: "python:3.7"

before_script:
  - python --version
  - pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install .[dev]

stages:
  - Test

pytest:
  stage: Test
  script:
  - pytest -n auto -x -rA
